### PR TITLE
BITE-1609: AWS IAM policy tests

### PR DESCRIPTION
**Pull request by paulschwarzenberger**
Tests of AWS IAM policies to ensure good practice:
- test for STS assume role of "AWS":"*"
- test for managed (attached) polices with * actions
- test for inline role policies with * actions

### CODE REVIEW

**Comment by paulschwarzenberger** [comment]
Corresponding PR in bitesize: https://github.com/pearsontechnology/bitesize/pull/937
This is only for CHANGELOG and PR-environment

**Comment by chrisbinnie** [comment]
Please see full comments: https://github.com/pearsontechnology/bitesize/pull/937

LGTM if the s3:* test was set to intentionally pass.

**Comment by paulschwarzenberger** [comment]
The python test for wildcards in policy actions currently includes the following exceptions:

{env}-nfs-server-s3-policy
{env}-stackstorm-{stackid}-server-elb-policy
{env}-stackstorm-{stackid}-server-elb-policy
Therefore the results of @chrisbinnie's testing are as expected

**Comment by devlinmr** [comment]
LGTM

**Comment by devlinmr** [comment]
LGTM

**Comment by geriBatai** [comment]
This is not the right place for these kinds of tests. We shouldn't block our pipeline if someone manually adds 0.0.0.0/0 into their personal cluster.

They are really useful in themselves, but they should live in a separate framework, preferably plugged into our monitoring (e.g. into Prometheus using [script exporter](https://github.com/adhocteam/script_exporter) ).

**Comment by paulschwarzenberger** [comment]
Discussed with @geriBatai and clarified that the purpose of the test is to prevent merging of unsafe code, which it does by only inspecting AWS state for the environment being tested, e.g. a Travis build. In addition agreed to raise a separate JIRA ticket for security monitoring, looking at all environments, which can detect manual configuration changes made after deployment.

**Pull request merged**
