### PR TITLE
[COPS-679] - Tests for SMTP settings in Grafana

### PR DESCRIPTION
**Pull request by thilinapiy**
I have update the grafana-rc to include SMTP settings in bitesize code. If that is correctly configured users should be able to successfully send a test mail via that. In the test case I'm doing the same thing using Grafana http-apis via a curl command.

### CODE REVIEW

**Comment by ufernis** [comment]
LGTM

**Comment by AndyMoore111** [comment]
how does it know this has been successful?

**Comment by ywchenbu** [comment]
It will send an email to the team email address showing Grafana has the correct SMTP for sending email. However, this does not allow Travis to decide whether it has been successful. Is there any other way to test it?

**Comment by thilinapiy** [comment]
Update the output validation, please check.

**Comment by ueberja** [comment]
LGTM

**Comment by thilinapiy** [comment]
Please refer to : https://github.com/pearsontechnology/kubernetes-tests/pull/44

**Pull request closed without merging**
